### ISSUE TITLE
Some accounts not working

### ISSUE THREAD

**Issue by mattttt** [raintank/ns1-app#5] opened 2016-05-12 16:51 UTC
This issue has been largely addressed via Slack, but will create a proper issue here to fix. 

Short version. Some accounts work great, other accounts (Vayl persona, and ns1 demo) do not. We're receiving permission denied, despite the permissions being the same on the NS1 side. 

Shannon can help troubleshoot, but would like to see the snap code and better error logging to troubleshoot. 

@woodsaj When you're back in action, this is one of our high priorities. It's a blocker before they can start testing with customers.

**Comment by woodsaj** [comment] 2016-05-14 18:13
fixed in https://github.com/raintank/raintank-apps/commit/840fb50b2dbed01302a1516521adb92d68405e34

**Comment by woodsaj** [comment] 2016-05-14 19:46
latest changes have been deployed.

**Closed as completed by woodsaj** 2016-05-14 19:46 UTC

**Comment by mattttt** [comment] 2016-05-15 12:44
Thanks! When you get a moment, can you fill me in on what the issue was and what was different about those accounts?

**Comment by woodsaj** [comment] 2016-05-15 15:58
The ns1 demo account had a rdns zone which had a "/" in the zone name.  As the zone name is included in the url it needed to be url encoded.

Dobt know avout vayl's  account.  You mention a "permission denied"  can you elaborate  on what you mean or add a screenshot.   The only error i am aware of is backend 404 error caused by the zone names.
